phrase:
  access_token: 32fa771343e5c24f018ee35487f02d66c1c874b6dfac18977bf9864327b2c020
  project_id: 99d5e98019f531ea35b7a85224de7738
  push:
    sources:
      - file: ./locales/en.json
        params:
          locale_id: 7588123b4682d13cde2a4771bc08ced9
          file_format: i18next_4
          tags: saferun-ui
          update_translations: true
          update_descriptions: true
          autotranslate: true
  pull:
    targets:
      - file: ./locales/de.json
        params:
          locale_id: 313de83e6657cb044650c8dda7b65c0a
          file_format: i18next_4
          include_unverified_translations: true
    targets:
      - file: ./locales/fr.json
        params:
          locale_id: 0699df24b6e907cdd303f3aa74cbc34a
          file_format: i18next_4
          include_unverified_translations: true
    targets:
      - file: ./locales/it.json
        params:
          locale_id: 4ba717f5d8b4cc084f461bd7aafdef20
          file_format: i18next_4
          include_unverified_translations: true
    targets:
      - file: ./locales/es.json
        params:
          locale_id: f3e6d40373f0b56631ff3cdac1eca5b0
          file_format: i18next_4
          include_unverified_translations: true
    targets:
      - file: ./locales/nl.json
        params:
          locale_id: 3967bc3f2295ccb4e2997b9b5c0192d5
          file_format: i18next_4
          include_unverified_translations: true